### PR TITLE
Revision

### PR DESCRIPTION
**Pull request by hatjek**
These are smaller modifications for the revision of the Besca manuscript.

### CODE REVIEW

**Review by alberto-valdeolivas — COMMENTED** [review]
It looks good to me. Just one minor point. In the `silhouette_computation` function there are some comments about improvements that should be made in the plots (see below). Do you plan to include this later? Or did you just forget to include these improvements?

Best,
Alberto

```
    **# TODO ADD PROPER TITLE/ AXIS/ MEAN OVERALL  and mean per label ?**
    ax1 = sns.violinplot(
        y=long_df_silhouette["label"], x=long_df_silhouette["silhouette"], scale="count"
    )
    matplotlib.pyplot.close()  **# Avoid plooting in function; bad practice**
    silhouette_results = silhouette_in(ax1, silhouette_avg)

    return silhouette_results
```

**Comment by hatjek** [comment]
Hi @alberto-valdeolivas ,

Thank you for looking into this. The silhouette was implemented by @ajulienla and I guess she will follow up on it once she is back. I would leave it as it is for the moment, but we can generate an issue on it. What do you think?

Best
Klas

**Comment by alberto-valdeolivas** [comment]
Hello @hatjek ! Okay, then I will approve the review, merge the pull request and include and issue as a potential future enhancement of the Silhouette function. Is that okay?

**Comment by hatjek** [comment]
Perfect, thanks!

**Review by alberto-valdeolivas — APPROVED** [review]

**Pull request merged**
