### PR TITLE
Lw

### PR DESCRIPTION
**Pull request by hatjek**
Dear @ajulienla @Artemis-R 

We want to merge the lw branch with the Auto-annot module into the master. Could you please have a look if it conflicts with your pull request?

Best
Klas and @luiswyss

### CODE REVIEW

**Comment by ajulienla** [comment]
@luiswyss  please use check_dl next time in all uploading functions. no h5ad is distributed at the moment within Besca. Thanks

**Comment by ajulienla** [comment]
@luiswyss ,
Should scvelo become a requirement ?

**Comment by luiswyss** [comment]
@ajulienla I see, thanks for the heads up. 
Yes, scvelo is required for correct loading of datasets for auto_annot.

**Comment by ajulienla** [comment]
This was reverted afterwards.

**Pull request merged**
