### PR TITLE
Pcs dev

### PR DESCRIPTION
**Pull request by swalpe**
1 - added some cell types and signatures
2 - added the "celltype" field in the gems export function, to ease matching of a signature with a cell type in various applications (and adjusted celltype anno workbook example)
3 - include a small section in celltype anno workbook exemplifying how one can search in scmongodb (if one has one) for similar clusters

### CODE REVIEW

**Review by hatjek — CHANGES_REQUESTED** [review]
Hi! You added quotation marks (") to these two files:
besca/datasets/genesets/CellNames_scseqCMs6_sigs.gmt 
besca/datasets/nomenclature/CellTypes_v1.tsv
which I would suggest to remove.
Best, Klas

**Comment by alberto-valdeolivas** [comment]
> Hi! You added quotation marks (") to these two files:
> besca/datasets/genesets/CellNames_scseqCMs6_sigs.gmt
> besca/datasets/nomenclature/CellTypes_v1.tsv
> which I would suggest to remove.
> Best, Klas

Hello, 

@swalpe,did you add the quotation marks only for the comments containing commas? You added some new signatures without the quotation marks. 

I do not mind if they have quotation marks or not, but I would suggest to make it consistent along the field in these files. 

Best,
Alberto.

**Comment by swalpe** [comment]
Indeed, thanks for spotting it! I edited the file in xls I guess the quotes were automatically introduced. Removed them all now.

**Review by alberto-valdeolivas — APPROVED** [review]
Approved after the removal of the quotation marks in the signature and cell nomenclature files

**Review by hatjek — APPROVED** [review]

**Pull request merged**
