### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by ajulienla**
+ segesterlope datasets has been renamed on zenodo. updated url

Moved everything to scanpy 1.6 so requirements updated for scanpy and anndata 
+ workbook calls to scanpy api renamed sc
+ forgotten scanpy.api on documentation

### CODE REVIEW

**Review by Artemis-R — APPROVED** [review]
Looks good. I will merge and then recompile the documentation.

**Comment by ajulienla** [comment]
@Artemis-R Here Besca  requires the new scanpy version. Should we do the 2.2.1 or 2.3 ?

**Comment by Artemis-R** [comment]
I’d do 2.3 I would do the new release with the updated documentation though. I had some issues compiling it yesterday but I’ll going to try and fix it today.

**Comment by ajulienla** [comment]
Yes exactly. Let me know if I missed some stuff

**Comment by Artemis-R** [comment]
I'm actually having issues compiling the documentation. Its a very strange error which is not properly getting displayed. I hope I can find it today. its definitely something that has changed in the last commits because it worked fine from a branch a little while back.

```
Extension error:
Handler <function process_automodsumm_generation at 0x7fa658ad11e0> for event 'builder-inited' threw an exception
make: *** [html] Error 2
```

Have you by change encountered this error already?

**Comment by ajulienla** [comment]
@Artemis-R , Yes I know this one, I struggled a lot to get pass it ....
Once it was an __init__ file with a missing coma (yes this is not a clear error message).

Other times, it was my environment. Previous commits that used to generate the documentation would not work either. So I regenerated the documentation from new environments.
I found this error extremelly frustrating and unclear.

**Pull request merged**
