### PR TITLE
Add additional scRNAseq R wrappers for preprocessing 

### PR DESCRIPTION
**Pull request by ansonrel**
Added R wrappers for scRNAseq preprocessing. The new functions are in `st/_wrapper_Rfuncs.py` and `pp/_wrapper_Rfuncs.py`. 

The installation is optional, and is explained in a new section of the README. It also describes the equivalent R functions. 

Their usage in the standard workflow notebook is also optional and is controlled with one single parameter, `r_methods`. The rest of the workflow shouldn't be affected by the usage of one or all of these methods in place of the standard methods.

### CODE REVIEW

**Review by hatjek — COMMENTED** [review]
Could you please change `r_methods = False` in the standard workflow notebook?

**Comment by ansonrel** [comment]
> Could you please change `r_methods = False` in the standard workflow notebook?

Done.

**Review by ajulienla — APPROVED** [review]

**Review by hatjek — COMMENTED** [review]
I was running the standard workflow including the new R functions, everything worked fine. I just realized that in the cell filtering it says:
"removed  0  cells that expressed  415.00000000000006 percent mitochondrial genes or more"
which is probably some problem with the percentage conversion.

**Comment by ansonrel** [comment]
> I was running the standard workflow including the new R functions, everything worked fine. I just realized that in the cell filtering it says:
> "removed 0 cells that expressed 415.00000000000006 percent mitochondrial genes or more"
> which is probably some problem with the percentage conversion.

Thanks for the bug report, it should be good now.

**Review by hatjek — APPROVED** [review]
I tested the standard workflow with and without R, works perfectly fine on the test dataset.

**Pull request merged**
